"""create period_cycles table

Revision ID: 8b4273b6d883
Revises: 3a3d81c94382
Create Date: 2025-08-25 18:47:41.180587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4273b6d883'
down_revision: Union[str, Sequence[str], None] = '3a3d81c94382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('period_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_period_date', sa.Date(), nullable=False),
    sa.Column('cycle_length', sa.Integer(), nullable=True),
    sa.Column('next_period_date', sa.Date(), nullable=True),
    sa.Column('ovulation_date', sa.Date(), nullable=True),
    sa.Column('symptoms', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_cycles_id'), 'period_cycles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_period_cycles_id'), table_name='period_cycles')
    op.drop_table('period_cycles')
    # ### end Alembic commands ###
